version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: zoom_utilities_app
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    volumes:
      - ./zoom_utilities:/app/zoom_utilities
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  node-bundler:
    build:
      context: .
      target: node-bundler
    restart: always
    container_name: zoom_utilities_node
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./zoom_utilities:/app/zoom_utilities # expose main django app so vite can output bundles here
      - ./zoom_utilities_vue:/app/zoom_utilities_vue
      - statics-volume:/static
    command: npm run watch
    stdin_open: true
    tty: true
volumes:
  statics-volume:
