autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
targetAverageUtilization: 100
affinity:
   podsSpanNodes: true

ingress:
  enabled: true
  tls:
    zoom-utils:
      secretName: apps.zoom.uw.edu-ingress-cert
      hosts:
        - apps.zoom.uw.edu
  hosts:
    zoom-utils:
      host: apps.zoom.uw.edu
      paths:
        - "/"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/client-body-buffer-size: "16K"
    nginx.ingress.kubernetes.io/ssl-ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA256"

lifecycle:
  enabled: true
  preStop:
    enabled: true
readiness:
  enabled: true

database:
  engine: null

repo: zoom-utilities
instance: prod

memcached:
  enabled: true
  replicaCount: 2
  updateStrategy:
    type: RollingUpdate

gcsCredentials:
  mounted: true
  secretName: apps.zoom.uw.edu-gcs-credentials

certs:
  mounted: true
  certPath: /certs/apps.zoom.uw.edu-ic.cert
  keyPath: /certs/apps.zoom.uw.edu-ic.key
  secretName: apps.zoom.uw.edu-ic-certs

environmentVariables:
  - name: CLUSTER_CNAME
    value: apps.zoom.uw.edu
  - name: AUTH
    value: SAML
  - name: SAML_ENTITY_ID
    value: https://apps.zoom.uw.edu/saml2
  - name: ENV
    value: prod
  - name: SESSION_BACKEND
    value: MEMCACHED

cronjob:
  enabled: false

daemon:
  enabled: false

externalSecrets:
  enabled: true
  secrets:
    - name: apps.zoom.uw.edu-secrets
      externalKey: zoom/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: storage-project-id
          property: storage-project-id
        - name: storage-bucket-name
          property: storage-bucket-name
    - name: apps.zoom.uw.edu-gcs-credentials
      externalKey: zoom/prod/gcs-credentials
      data:
        - name: credentials.json
          property: credentials.json
    - name: apps.zoom.uw.edu-ic-certs
      externalKey: zoom/prod/ic-certs
      data:
        - name: apps.zoom.uw.edu-ic.cert
          property: apps.zoom.uw.edu-ic.cert
        - name: apps.zoom.uw.edu-ic.key
          property: apps.zoom.uw.edu-ic.key
    - name: apps.zoom.uw.edu-uw-idp-cert
      externalKey: axdd/kv/data/idp-cert
      data:
        - name: uw-idp-cert
          property: cert

environmentVariablesSecrets:
  django-secret:
    name: DJANGO_SECRET
    secretName: apps.zoom.uw.edu-secrets
    secretKey: django-secret
  storageBucketName:
    name: STORAGE_BUCKET_NAME
    secretName: apps.zoom.uw.edu-secrets
    secretKey: storage-bucket-name
  storageProjectId:
    name: STORAGE_PROJECT_ID
    secretName: apps.zoom.uw.edu-secrets
    secretKey: storage-project-id
  samlSPCert:
    name: SP_CERT
    secretName: apps.zoom.uw.edu-ic-certs
    secretKey: apps.zoom.uw.edu-ic.cert
  samlIDPCert:
    name: IDP_CERT
    secretName: apps.zoom.uw.edu-uw-idp-cert
    secretKey: uw-idp-cert
